[package]
name = "lumen-core"
version = "0.1.0"
edition = "2024"

[dependencies]
lumen-primitives = { path = "../primitives" }
lumen-fingerprints-lib = { path = "../fingerprints" }
bitcoin = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["float_roundtrip"] }
toml = "0.8"
zstd = "0.13"
