[book]
title = "Lumen Fingerprints"
authors = ["bc1cindy", "built on tx-indexer (© Armin Sabouri and Yuval Kogman)"]
src = "src"
language = "en"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/fungi-protocol"
